spring.application.name=item_service

server.port=8090

spring.datasource.url= jdbc:postgresql://localhost:5433/db_chyone_store
spring.datasource.username = postgres
spring.datasource.password = rechyone

spring.jpa,hibernate.ddl.auto = update
