spring.application.name=item_service

server.port=8090

spring.datasource.url= jdbc:postgresql://localhost:5433/db_chyone_store
spring.datasource.username = postgres
spring.datasource.password = rechyone

spring.jpa,hibernate.ddl.auto = update

email.sender = hikaruryukiri@gmail.com
email.password = ihib jiwd fyig bcjk

smtp.host=smtp.gmail.com
smtp.port=587

spring.mail.host=${smtp.host}
spring.mail.port=${smtp.port}
spring.mail.username=${email.sender}
spring.mail.password=${email.password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true